import {
	useAppInsightsContext,
	useTrackEvent,
} from "@microsoft/applicationinsights-react-js";
import Head from "next/head";
import { FormEvent, useEffect, useState } from "react";

export default function Test() {
	const appInsights = useAppInsightsContext();
	const [value, setValue] = useState(0);
	const [inputValue, setInputValue] = useState("");
	const trackValue = useTrackEvent(appInsights, "Track Value", value);
	const trackInputValue = useTrackEvent(
		appInsights,
		"Track Input Value",
		inputValue
	);

	useEffect(() => {
		trackValue(value);
	}, [value, trackValue]);

	const changeValue = (operation: string): void => {
		if (operation === "increase") {
			setValue((prev) => prev + 1);
		} else {
			setValue((prev) => prev - 1);
		}
	};

	const handleSubmit = (event: FormEvent<HTMLFormElement>): void => {
		event.preventDefault();
		//@ts-ignore
		trackInputValue(event.currentTarget[0].value);
		alert("Submitted");
	};

	return (
		<div>
			<Head>
				<title>Test Next Analytics Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Testing value is {value}</h1>
			<button onClick={() => changeValue("decrease")}>Decrease</button>
			<button onClick={() => changeValue("increase")}>Increase</button>
			<form onSubmit={(e) => handleSubmit(e)}>
				<label htmlFor="name">Name</label>
				<input
					type="text"
					name="name"
					value={inputValue}
					placeholder="enter your name"
					onChange={(e) => setInputValue(e.target.value)}
				/>
				<button type="submit">Submit</button>
			</form>
		</div>
	);
}
